### ISSUE TITLE
Frame Rates

### ISSUE THREAD

**Issue by maudhelen** [maudhelen/CompVision-MapNavigator#8]
Find a way to make the moving of both cursor and frame smoother. Open task :)
- run the app.py in google maps, try to drag etc. and you'll see it's a bit slow

**File to edit** I don't know how you'd go forward, but at least logic needs to be added in "app.py" since thats where we are capturing the video.

**Comment by mirandadrummond** [comment]
completed in mauds laptop due to issues with branch protection
