### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by maudhelen** [maudhelen/CompVision-MapNavigator#9]
**Maud**
1. Add photo of "pointing up" with description of what that would do 

  - **File: image_marking.ipynb**
  1. Upload the jpg to images folder
  2. add the image name to the image array
  3. run the code
  4. add the photolink in README
  5. Add description in README

2. Write about architecture 
- Models used for both (keras and landmarks) **Miranda**
- Brief explaination of Logic (hand_gestures.py) **Samuel**
- Main structure of files **Samuel** (How to run the difefrent etc)

**Comment by mirandadrummond** [comment]
complete
